baseURL = 'https://krizsx.github.io'
languageCode = 'zh-CN'
title = 'My New Hugo Site'
theme = 'github-style'

[params]
author = "KrizsX"
description = "å°½é‡ä¸æ‘†çƒ‚"
github = "krizsx"
email = "cb.kris.bj@gmail.com"
url = "https://krizsx.github.io/"
avatar = "/img/avator.jpeg"
#   keywords = "blog, google analytics"
#   rss = true
lastmod = true
userStatusEmoji = "ğŸ‘»"
# favicon = "/images/avator.jpeg"
#   location = "China"
#   enableGitalk = true

# [[params.links]]
# title = "Link"
# href = "https://github.com/krizsx"

[frontmatter]
lastmod = ["lastmod", ":fileModTime", ":default"]
